// #Sireum

package bless.runtimemonitor

import org.sireum._
import bless._

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

@enum object ObservationKind {
  "PG_i_Instance_pp_t_postInit"
  "PG_i_Instance_pp_t_preCompute"
  "PG_i_Instance_pp_t_postCompute"
  "PG_i_Instance_pp_rc_postInit"
  "PG_i_Instance_pp_rc_preCompute"
  "PG_i_Instance_pp_rc_postCompute"
}
