// #Sireum 
   // generated by BLESS v3.2.1 at Tue Nov 14 03:54:35 CST 2023 from ["mark", "AtrialMarker"]

package bless.mark

import org.sireum._
import bless._
import org.sireum.S64._
import org.sireum.F64._
import art.Art

// This file will not be overwritten so is safe to edit

// This is a type skeleton as HAMR doesn't know how to translate mark::AtrialMarker

object AtrialMarker {
  def example(): mark.AtrialMarker =
    { return mark.AtrialMarker(atrialMarker_enum.ap) }
}

@datatype class AtrialMarker(
  value : atrialMarker_enum.Type) {
}

object AtrialMarker_Payload {
  def example(): AtrialMarker_Payload = {
    return AtrialMarker_Payload(mark.AtrialMarker.example())
  }
}

@datatype class AtrialMarker_Payload(value: mark.AtrialMarker) extends art.DataContent

@enum object atrialMarker_enum {
  "ap" 
  "as" 
  "at" 
  "ras"
}