// #Sireum 
   // generated by BLESS v3.2.1 at Tue Nov 14 03:54:35 CST 2023 from ["mark", "ExtraordinaryMarker"]

package bless.mark

import org.sireum._
import bless._
import org.sireum.S64._
import org.sireum.F64._
import art.Art

// This file will not be overwritten so is safe to edit

// This is a type skeleton as HAMR doesn't know how to translate mark::ExtraordinaryMarker

object ExtraordinaryMarker {
  def example(): mark.ExtraordinaryMarker =
    { return mark.ExtraordinaryMarker(extraordinaryMarker_enum.atr_dct) }
}

@datatype class ExtraordinaryMarker(
  value : extraordinaryMarker_enum.Type) {
}

object ExtraordinaryMarker_Payload {
  def example(): ExtraordinaryMarker_Payload = {
    return ExtraordinaryMarker_Payload(mark.ExtraordinaryMarker.example())
  }
}

@datatype class ExtraordinaryMarker_Payload(value: mark.ExtraordinaryMarker) extends art.DataContent

@enum object extraordinaryMarker_enum {
  "atr_dct" 
  "atr_fb" 
  "atr_end"
}