// #Sireum 
   // generated by BLESS v3.2.1 at Tue Nov 14 03:54:35 CST 2023 from ["mark", "VentricularlMarker"]

package bless.mark

import org.sireum._
import bless._
import org.sireum.S64._
import org.sireum.F64._
import art.Art

// This file will not be overwritten so is safe to edit

// This is a type skeleton as HAMR doesn't know how to translate mark::VentricularlMarker

object VentricularlMarker {
  def example(): mark.VentricularlMarker =
    { return mark.VentricularlMarker(ventricularMarker_enum.vp) }
}

@datatype class VentricularlMarker(
  value : ventricularMarker_enum.Type) {
}

object VentricularlMarker_Payload {
  def example(): VentricularlMarker_Payload = {
    return VentricularlMarker_Payload(mark.VentricularlMarker.example())
  }
}

@datatype class VentricularlMarker_Payload(value: mark.VentricularlMarker) extends art.DataContent

@enum object ventricularMarker_enum {
  "vp" 
  "vs" 
  "pvc" 
  "rvs"
}