// #Sireum 
   // generated by BLESS v3.2.1 at Tue Nov 14 03:54:35 CST 2023 from ["PACE_Data", "CCcount"]

package bless.PACE_Data

import org.sireum._
import bless._
import org.sireum.S64._
import org.sireum.F64._
import art.Art

// This file will not be overwritten so is safe to edit

// This is a type skeleton as HAMR doesn't know how to translate PACE_Data::CCcount

object CCcount {
  def example(): PACE_Data.CCcount =
    { return PACE_Data.CCcount(s64"10") }
}

@datatype class CCcount(
  whole : S64) {
}

object CCcount_Payload {
  def example(): CCcount_Payload = {
    return CCcount_Payload(PACE_Data.CCcount.example())
  }
}

@datatype class CCcount_Payload(value: PACE_Data.CCcount) extends art.DataContent

