// #Sireum 
   // generated by BLESS v3.2.1 at Tue Nov 14 03:54:35 CST 2023 from ["PACE_Data", "milliG"]

package bless.PACE_Data

import org.sireum._
import bless._
import org.sireum.S64._
import org.sireum.F64._
import art.Art

// This file will not be overwritten so is safe to edit

// This is a type skeleton as HAMR doesn't know how to translate PACE_Data::milliG

object milliG {
  def example(): PACE_Data.milliG =
    { return PACE_Data.milliG(f64"0.2") }
}

@datatype class milliG(
  milliG : F64) {
}

object milliG_Payload {
  def example(): milliG_Payload = {
    return milliG_Payload(PACE_Data.milliG.example())
  }
}

@datatype class milliG_Payload(value: PACE_Data.milliG) extends art.DataContent

