// #Sireum 
   // generated by BLESS v3.2.1 at Tue Nov 14 03:54:35 CST 2023 from ["PACE_Data", "ms"]

package bless.PACE_Data

import org.sireum._
import bless._
import org.sireum.S64._
import org.sireum.F64._
import art.Art

// This file will not be overwritten so is safe to edit

// This is a type skeleton as HAMR doesn't know how to translate PACE_Data::ms

object ms {
  def example(): PACE_Data.ms =
    { return PACE_Data.ms(f64"0.6") }
}

@datatype class ms(
  ms : F64) {
}

object ms_Payload {
  def example(): ms_Payload = {
    return ms_Payload(PACE_Data.ms.example())
  }
}

@datatype class ms_Payload(value: PACE_Data.ms) extends art.DataContent

