// #Sireum 
   // generated by BLESS v3.2.1 at Tue Nov 14 03:54:35 CST 2023 from ["PACE_Data", "percent"]

package bless.PACE_Data

import org.sireum._
import bless._
import org.sireum.S64._
import org.sireum.F64._
import art.Art

// This file will not be overwritten so is safe to edit

// This is a type skeleton as HAMR doesn't know how to translate PACE_Data::percent

object percent {
  def example(): PACE_Data.percent =
    { return PACE_Data.percent(f64"0.9") }
}

@datatype class percent(
  scalar : F64) {
}

object percent_Payload {
  def example(): percent_Payload = {
    return percent_Payload(PACE_Data.percent.example())
  }
}

@datatype class percent_Payload(value: PACE_Data.percent) extends art.DataContent

