// #Sireum 
   // generated by BLESS v3.2.1 at Tue Nov 14 03:54:35 CST 2023 from ["PACE_Data", "rf"]

package bless.PACE_Data

import org.sireum._
import bless._
import org.sireum.S64._
import org.sireum.F64._
import art.Art

// This file will not be overwritten so is safe to edit

// This is a type skeleton as HAMR doesn't know how to translate PACE_Data::rf

object rf {
  def example(): PACE_Data.rf =
    { return PACE_Data.rf(f64"0.7") }
}

@datatype class rf(
  rf : F64) {
}

object rf_Payload {
  def example(): rf_Payload = {
    return rf_Payload(PACE_Data.rf.example())
  }
}

@datatype class rf_Payload(value: PACE_Data.rf) extends art.DataContent

