// #Sireum 
   // generated by BLESS v3.2.1 at Tue Nov 14 03:54:35 CST 2023 from ["PACE_Data", "second"]

package bless.PACE_Data

import org.sireum._
import bless._
import org.sireum.S64._
import org.sireum.F64._
import art.Art

// This file will not be overwritten so is safe to edit

// This is a type skeleton as HAMR doesn't know how to translate PACE_Data::second

object second {
  def example(): PACE_Data.second =
    { return PACE_Data.second(f64"0.8") }
}

@datatype class second(
  s : F64) {
}

object second_Payload {
  def example(): second_Payload = {
    return second_Payload(PACE_Data.second.example())
  }
}

@datatype class second_Payload(value: PACE_Data.second) extends art.DataContent

