// #Sireum 
   // generated by BLESS v3.2.4 at Fri Mar 15 16:09:26 CDT 2024 from ["vvi_mode", "CardiacDuration"]

package bless.vvi_mode

import org.sireum._
import bless._
import org.sireum.S64._
import org.sireum.F64._
import art.Art

// This file will not be overwritten so is safe to edit

// This is a type skeleton as HAMR doesn't know how to translate vvi_mode::CardiacDuration

object CardiacDuration {
  def example(): vvi_mode.CardiacDuration =
    { return vvi_mode.CardiacDuration(f64"0.4") }
}

@datatype class CardiacDuration(
  ms : F64) {
}

object CardiacDuration_Payload {
  def example(): CardiacDuration_Payload = {
    return CardiacDuration_Payload(vvi_mode.CardiacDuration.example())
  }
}

@datatype class CardiacDuration_Payload(value: vvi_mode.CardiacDuration) extends art.DataContent

