// #Sireum

package bless.vvi_mode

import org.sireum._
import bless._
import bless.util.Container

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

// containers for the pre and post state values of ports and state variables

@sig trait RateControl_pp_rc_PreState_Container extends Container {
}

// container for incoming ports
@datatype class RateControl_pp_rc_PreState_Container_P (
  ) extends RateControl_pp_rc_PreState_Container

// container for incoming ports and state variables
@datatype class RateControl_pp_rc_PreState_Container_PS (
  ) extends RateControl_pp_rc_PreState_Container

@sig trait RateControl_pp_rc_PostState_Container extends Container {
  def api_lrl: vvi_mode.CardiacDuration
  def api_vrp: vvi_mode.CardiacDuration
}

// container for outgoing ports
@datatype class RateControl_pp_rc_PostState_Container_P (
  val api_lrl: vvi_mode.CardiacDuration,
  val api_vrp: vvi_mode.CardiacDuration) extends RateControl_pp_rc_PostState_Container

// container for outgoing ports and state variables
@datatype class RateControl_pp_rc_PostState_Container_PS (
  val api_lrl: vvi_mode.CardiacDuration,
  val api_vrp: vvi_mode.CardiacDuration) extends RateControl_pp_rc_PostState_Container
