// #Sireum

package bless.vvi_mode

import org.sireum._
import bless._
import bless.util.Container

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

// containers for the pre and post state values of ports and state variables

@sig trait VVI_i_pp_t_PreState_Container extends Container {
  def api_h: Option[art.Empty]
  def api_s: Option[art.Empty]
  def api_lrl: vvi_mode.CardiacDuration
  def api_vrp: vvi_mode.CardiacDuration
}

// container for incoming ports
@datatype class VVI_i_pp_t_PreState_Container_P (
  val api_h: Option[art.Empty],
  val api_s: Option[art.Empty],
  val api_lrl: vvi_mode.CardiacDuration,
  val api_vrp: vvi_mode.CardiacDuration) extends VVI_i_pp_t_PreState_Container

// container for incoming ports and state variables
@datatype class VVI_i_pp_t_PreState_Container_PS (
  val api_h: Option[art.Empty],
  val api_s: Option[art.Empty],
  val api_lrl: vvi_mode.CardiacDuration,
  val api_vrp: vvi_mode.CardiacDuration) extends VVI_i_pp_t_PreState_Container

@sig trait VVI_i_pp_t_PostState_Container extends Container {
  def api_n: Option[art.Empty]
  def api_p: Option[art.Empty]
}

// container for outgoing ports
@datatype class VVI_i_pp_t_PostState_Container_P (
  val api_n: Option[art.Empty],
  val api_p: Option[art.Empty]) extends VVI_i_pp_t_PostState_Container

// container for outgoing ports and state variables
@datatype class VVI_i_pp_t_PostState_Container_PS (
  val api_n: Option[art.Empty],
  val api_p: Option[art.Empty]) extends VVI_i_pp_t_PostState_Container
